

export const ACTION_GET_POSTS_STARTED = "GET_POSTS_STARTED";
export const ACTION_GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const ACTION_GET_POSTS_FAILED = "GET_POSTS_FAILED";

export const ACTION_CREATE_POST_STARTED = "CREATE_POST_STARTED";
export const ACTION_CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
